### ISSUE TITLE
这是一个非常好的项目, 但是https://github.com/Syencil/tensorflow-yolov3没有了，能否重新上传您的项目呢，我使用原版代码无法完成.pb到.onnx的转换

### ISSUE THREAD

**Issue by Byronnar** [Syencil/tensorRT#29]
如题: https://github.com/Syencil/tensorflow-yolov3没有了，能否重新上传您的项目，我使用原版代码无法完成.pb到.onnx的转换,您可以分享一下么

**Comment by Syencil** [comment]
需要改动的地方我已经直接在readme中写了 你可以参考一下

**Comment by Byronnar** [comment]
非常感谢您的回复, 转换onnx已经成功了, 但是NMS跟动态数组没有修改, tensorrt一直转换不了. 请问您是怎么转换成tensorrt的呢

谢谢!!!

**Comment by Syencil** [comment]
转成onnx了不就可以直接用trt读取了 或者用onnx2trt转成engine

**Comment by Byronnar** [comment]
您好, 是这样的, 我转换成onnx没有修改成 decode_full_shape,  因为一修改成decode_full_shape, freeze就没法使用了.报这个错, tensorflow版本1.13.1.. 您之前转换没这个问题么..

```
Traceback (most recent call last):
  File "/home/byronnar/anaconda3/envs/dev/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 558, in make_tensor_proto
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "/home/byronnar/anaconda3/envs/dev/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 558, in <listcomp>
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "/home/byronnar/anaconda3/envs/dev/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 65, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "freeze_graph.py", line 14, in <module>
    model = YOLOV3(input_data, trainable=False)
  File "/home/byronnar/yolo3/tensorflow-yolov3-serving-deploy/core/yolov3.py", line 42, in __init__
    self.pred_sbbox = self.decode_full_shape( self.conv_sbbox, self.anchors[0], self.strides[0] )
  File "/home/byronnar/yolo3/tensorflow-yolov3-serving-deploy/core/yolov3.py", line 154, in decode_full_shape
    name="reshape" )
  File "/home/byronnar/anaconda3/envs/dev/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 7715, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/home/byronnar/anaconda3/envs/dev/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 530, in _apply_op_helper
    raise err
  File "/home/byronnar/anaconda3/envs/dev/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 527, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/home/byronnar/anaconda3/envs/dev/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1224, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/byronnar/anaconda3/envs/dev/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 305, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/byronnar/anaconda3/envs/dev/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 246, in constant
    allow_broadcast=True)
  File "/home/byronnar/anaconda3/envs/dev/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 284, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/home/byronnar/anaconda3/envs/dev/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 562, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <class 'tuple'> to Tensor. Contents: (None, None, None, 3, 85). Consider casting elements to a supported type.
```
但是如果不修改这个直接转换成onnx的话, trt没法使用, 因为它不支持tf.cast等操作.

**Comment by Syencil** [comment]
freeze重写一下就行了 这个很简单 参考tf转onnx的官方文档
