### ISSUE TITLE
PSEnet: onnx转pb模型

### ISSUE THREAD

**Issue by Tian14267** [Syencil/tensorRT#5]
作者你好，我有一个问题，是关于把pse算法的onnx模型转换到pb模型，遇到的一个问题：
**Traceback (most recent call last):
  File "/home/fffan/fffan_files/Experiment/Example/onnx2pb/onnx2pb.py", line 45, in <module>
    onnx2pb_2(onnx_input_path)
  File "/home/fffan/fffan_files/Experiment/Example/onnx2pb/onnx2pb.py", line 14, in onnx2pb_2
    tf_rep = prepare(model)
  File "/home/fffan/下载/onnx-tensorflow-tf-1.x/onnx_tf/backend.py", line 65, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "/home/fffan/下载/onnx-tensorflow-tf-1.x/onnx_tf/backend.py", line 85, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "/home/fffan/下载/onnx-tensorflow-tf-1.x/onnx_tf/backend.py", line 146, in _onnx_graph_to_tensorflow_rep
    strict=strict)
  File "/home/fffan/下载/onnx-tensorflow-tf-1.x/onnx_tf/backend.py", line 241, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "/home/fffan/下载/onnx-tensorflow-tf-1.x/onnx_tf/handlers/handler.py", line 60, in handle
    cls.args_check(node, **kwargs)
  File "/home/fffan/下载/onnx-tensorflow-tf-1.x/onnx_tf/handlers/backend/resize.py", line 89, in args_check
    "Tensorflow")
  File "/home/fffan/下载/onnx-tensorflow-tf-1.x/onnx_tf/common/exception.py", line 50, in __call__
    raise self._func(self.get_message(op, framework))
RuntimeError: Resize coordinate_transformation_mode=pytorch_half_pixel is not supported in Tensorflow.**
我没看到载pytorch有关pytorch_half_pixel这个的使用，但是转换模型的时候总是这个错。请问作者能不能解决这个问题？
非常期待作者的回复。

**Comment by Syencil** [comment]
> 作者你好，我有一个问题，是关于把pse算法的onnx模型转换到pb模型，遇到的一个问题：
> **Traceback (most recent call last):
> File "/home/fffan/fffan_files/Experiment/Example/onnx2pb/onnx2pb.py", line 45, in
> onnx2pb_2(onnx_input_path)
> File "/home/fffan/fffan_files/Experiment/Example/onnx2pb/onnx2pb.py", line 14, in onnx2pb_2
> tf_rep = prepare(model)
> File "/home/fffan/下载/onnx-tensorflow-tf-1.x/onnx_tf/backend.py", line 65, in prepare
> return cls.onnx_model_to_tensorflow_rep(model, strict)
> File "/home/fffan/下载/onnx-tensorflow-tf-1.x/onnx_tf/backend.py", line 85, in onnx_model_to_tensorflow_rep
> return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
> File "/home/fffan/下载/onnx-tensorflow-tf-1.x/onnx_tf/backend.py", line 146, in _onnx_graph_to_tensorflow_rep
> strict=strict)
> File "/home/fffan/下载/onnx-tensorflow-tf-1.x/onnx_tf/backend.py", line 241, in _onnx_node_to_tensorflow_op
> return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
> File "/home/fffan/下载/onnx-tensorflow-tf-1.x/onnx_tf/handlers/handler.py", line 60, in handle
> cls.args_check(node, **kwargs) File "/home/fffan/下载/onnx-tensorflow-tf-1.x/onnx_tf/handlers/backend/resize.py", line 89, in args_check "Tensorflow") File "/home/fffan/下载/onnx-tensorflow-tf-1.x/onnx_tf/common/exception.py", line 50, in **call** raise self._func(self.get_message(op, framework)) RuntimeError: Resize coordinate_transformation_mode=pytorch_half_pixel is not supported in Tensorflow.**
> 我没看到载pytorch有关pytorch_half_pixel这个的使用，但是转换模型的时候总是这个错。请问作者能不能解决这个问题？
> 非常期待作者的回复。

这个问题是在F.interpolate里面出现的。因为在不同框架中上采样的具体中，随着采样点的选择不同导致结果不同。在torch转onnx的过程中，nearest的采样方式被定义为asymmetric，bilinear中有一个align_corners的参数，设置为false的时候会被定义为pytorch_half_pixel，true的时候则为align_corners采样方式。
这个定义你可以在torch->onnx->opset11算子定义的那个文件里面找到。
解决方法可以是将onnx对应节点用mode=align_corners的bilinear操作代替，不过这样就会损失精度。
